[tool.poetry]
name = "cargo-bloat-backend"
version = "0.1.0"
description = ""
authors = ["Tom Forbes <tom@tomforb.es>"]

packages = [
    { include = "app.py" },
]

[tool.poetry.dependencies]
python = "^3.7"
chalice = "^1.12.0"
sqlalchemy = {extras = ["postgresql_psycopg2binary"], version = "^1.3.12"}

[tool.poetry.dev-dependencies]
pytest-chalice = "^0.0.4"
pytest = "^5.3.2"
invoke = "^1.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
