service: cargo-bloat-backend
provider:
  name: aws
  runtime: rust
  memorySize: 128
  stage: dev
  region: us-east-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  individually: true

plugins:
  - serverless-rust
  - serverless-offline

functions:
  install:
    handler: install
    events:
      - http:
          path: /install
          method: get
  ingest:
    handler: ingest
    events:
      - http:
          path: /ingest
          method: get
