service: cargo-bloat-backend
provider:
  name: aws
  runtime: rust
  memorySize: 128
  stage: dev
  region: us-east-1

  environment:
    DATABASE_URL: ${env:DATABASE_URL}

package:
  individually: true

plugins:
  - serverless-rust
  - serverless-offline

functions:
  install:
    handler: cargo-bloat-backend.install
    events:
      - http:
          path: /install
          method: get
  ingest:
    handler: cargo-bloat-backend.ingest
    events:
      - http:
          path: /ingest
          method: get
