name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Cache setup:
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'
      - uses: dschep/install-poetry-action@v1.2
      - run: poetry install
#      - run: poetry run invoke deploy