name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSDK_CORE_PROJECT: cargo-bloat
    steps:
      - uses: actions/checkout@v1
      - run: cat ${GITHUB_EVENT_PATH}
      # Cache setup:
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'
      - uses: dschep/install-poetry-action@v1.2
      - run: poetry install
      - run: poetry run pytest
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: poetry run invoke deploy
