name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Cache setup:
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v1
      - uses: dschep/install-poetry-action@v1.2
      - run: poetry install
      - run: poetry run invoke deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#env:
#DATABASE_URL: ${{ secrets.DATABASE_URL }}
#DJANGO_SETTINGS_MODULE: app_name.settings.dev
#SECRET_KEY: ${{ secrets.SECRET_KEY }}
#PORT: 8000
#PG_DB: ${{ secrets.PG_DB }}
#PG_PASS: ${{ secrets.PG_PASS }}
#PG_USER: ${{ secrets.USER }}
#
#steps:
#- uses: actions/checkout@v1
#- name: Build the docker-compose stack
#run: docker-compose up -d
#- name: Sleep
#uses: jakejarvis/wait-action@master
#with:
#time: '60s'
#- name: Check running containers
#run: docker ps
#- name: Run test suite
#run: docker exec backend pytest --skip-auth